// Navigation and Language Support JavaScript

const translations = {
  en: {
    brand: "MyApp",
    home: "Home",
    portfolio: "Portfolio",
    team: "Team",
    blog: "Blog",
    aboutUs: "About Us",
    education: "Education",
    services: "Services",
    skills: "Skills",
    experience: "Experience",
    contact: "Contact",
    language: "Language",

    // Section Content
    homeTitle: "Welcome Home",
    homeDesc: "Explore our innovative platform designed to help you grow and succeed. With cutting-edge technology and dedicated support, we're here to serve you.",

    aboutTitle: "About Us",
    aboutDesc: "We are passionate about creating solutions that make a difference. Our team consists of experienced professionals dedicated to excellence.",
    aboutMission: "Our Mission",
    aboutMissionDesc: "To empower individuals and businesses with tools and knowledge to achieve their goals.",
    aboutVision: "Our Vision",
    aboutVisionDesc: "A world where technology and innovation create unlimited opportunities.",

    educationTitle: "Education",
    educationDesc: "Invest in your future with our comprehensive educational programs.",
    course1: "Web Development",
    course1Desc: "Learn HTML, CSS, JavaScript, and modern frameworks.",
    course2: "Mobile Apps",
    course2Desc: "Create powerful applications for iOS and Android.",
    course3: "Data Science",
    course3Desc: "Master data analysis, visualization, and machine learning.",

    servicesTitle: "Our Services",
    servicesDesc: "We provide a wide range of professional services tailored to your needs.",
    service1: "Consulting",
    service1Desc: "Expert guidance to streamline your business operations.",
    service2: "Development",
    service2Desc: "Custom solutions built with latest technologies.",
    service3: "Support",
    service3Desc: "24/7 dedicated support for all our clients.",

    skillsTitle: "Our Skills",
    skillsDesc: "Expertise across multiple domains and technologies.",
    skill1: "Full Stack Development",
    skill2: "Cloud Architecture",
    skill3: "UI/UX Design",
    skill4: "DevOps & Deployment",
    skill5: "Database Management",
    skill6: "API Development",

    experienceTitle: "Experience",
    experienceDesc: "Years of delivering quality solutions to diverse clients.",
    exp1: "10+ Years Industry Experience",
    exp2: "500+ Projects Completed",
    exp3: "100+ Satisfied Clients",
    exp4: "50+ Team Members",

    contactTitle: "Get In Touch",
    contactDesc: "Have questions? We'd love to hear from you. Get in touch with us today.",
    contactEmail: "Email: salimabdu759@gmail.com",
    contactPhone: "Phone: +250739390715-0735281339",
    contactAddress: "Address:  Main idea, City, kigali Rwanda",
    sendMessage: "Send Message",
  },
  fr: {
    brand: "MonApp",
    home: "Accueil",
    portfolio: "Portfolio",
    team: "Équipe",
    blog: "Blog",
    aboutUs: "À Propos",
    education: "Éducation",
    services: "Services",
    skills: "Compétences",
    experience: "Expérience",
    contact: "Nous Contacter",
    language: "Langue",

    homeTitle: "Bienvenue à l'Accueil",
    homeDesc: "Explorez notre plateforme innovante conçue pour vous aider à grandir et à réussir. Avec une technologie de pointe et un soutien dévoué, nous sommes là pour vous servir.",

    aboutTitle: "À Propos de Nous",
    aboutDesc: "Nous sommes passionnés par la création de solutions qui font une différence. Notre équipe est composée de professionnels expérimentés dédiés à l'excellence.",
    aboutMission: "Notre Mission",
    aboutMissionDesc: "Autonomiser les individus et les entreprises avec des outils et des connaissances pour atteindre leurs objectifs.",
    aboutVision: "Notre Vision",
    aboutVisionDesc: "Un monde où la technologie et l'innovation créent des opportunités illimitées.",

    educationTitle: "Éducation",
    educationDesc: "Investissez dans votre avenir avec nos programmes éducatifs complets.",
    course1: "Développement Web",
    course1Desc: "Apprenez HTML, CSS, JavaScript et les frameworks modernes.",
    course2: "Applications Mobiles",
    course2Desc: "Créez des applications puissantes pour iOS et Android.",
    course3: "Science des Données",
    course3Desc: "Maîtrisez l'analyse de données, la visualisation et l'apprentissage automatique.",

    servicesTitle: "Nos Services",
    servicesDesc: "Nous fournissons une large gamme de services professionnels adaptés à vos besoins.",
    service1: "Conseil",
    service1Desc: "Conseils d'experts pour rationaliser vos opérations commerciales.",
    service2: "Développement",
    service2Desc: "Solutions personnalisées construites avec les dernières technologies.",
    service3: "Soutien",
    service3Desc: "Support dédié 24h/24 pour tous nos clients.",

    skillsTitle: "Nos Compétences",
    skillsDesc: "Expertise dans plusieurs domaines et technologies.",
    skill1: "Développement Full Stack",
    skill2: "Architecture Cloud",
    skill3: "Design UI/UX",
    skill4: "DevOps & Déploiement",
    skill5: "Gestion de Base de Données",
    skill6: "Développement d'API",

    experienceTitle: "Expérience",
    experienceDesc: "Des années à fournir des solutions de qualité à des clients divers.",
    exp1: "10+ Ans d'Expérience Secteur",
    exp2: "500+ Projets Complétés",
    exp3: "100+ Clients Satisfaits",
    exp4: "50+ Membres de l'Équipe",

    contactTitle: "Contactez-Nous",
    contactDesc: "Vous avez des questions? Nous serions heureux de vous entendre. Contactez-nous dès aujourd'hui.",
    contactEmail: "E-mail: salimabdu759@gmail.com",
    contactPhone: "Téléphone: +250739390715-0735281339",
    contactAddress: "Adresse:  Main idea, City, kigali Rwanda",
    sendMessage: "Envoyer un Message",
  },
  ar: {
    brand: "تطبيقي",
    home: "الرئيسية",
    aboutUs: "عن",
    education: "التعليم",
    services: "الخدمات",
    skills: "المهارات",
    experience: "التجربة",
    contact: "الاتصال",
    language: "اللغة",

    homeTitle: "مرحبا بك في الرئيسية",
    homeDesc: "استكشف منصتنا المبتكرة المصممة لمساعدتك على النمو والنجاح. مع تقنية متقدمة ودعم مخصص، نحن هنا لخدمتك.",

    aboutTitle: "عن الشركة",
    aboutDesc: "نحن متحمسون لإنشاء حلول تحدث فرقًا. يتكون فريقنا من محترفين ذوي خبرة مكرسين للتميز.",
    aboutMission: "مهمتنا",
    aboutMissionDesc: "تمكين الأفراد والشركات بالأدوات والمعرفة لتحقيق أهدافهم.",
    aboutVision: "رؤيتنا",
    aboutVisionDesc: "عالم حيث تخلق التكنولوجيا والابتكار فرصًا غير محدودة.",

    educationTitle: "التعليم",
    educationDesc: "استثمر في مستقبلك ببرامجنا التعليمية الشاملة.",
    course1: "تطوير الويب",
    course1Desc: "تعلم HTML و CSS و JavaScript والأطر الحديثة.",
    course2: "تطبيقات الهاتف المحمول",
    course2Desc: "إنشاء تطبيقات قوية لنظام iOS و Android.",
    course3: "علوم البيانات",
    course3Desc: "إتقان تحليل البيانات والتصور والتعلم الآلي.",

    servicesTitle: "خدماتنا",
    servicesDesc: "نوفر مجموعة واسعة من الخدمات المهنية المصممة حسب احتياجاتك.",
    service1: "الاستشارة",
    service1Desc: "إرشادات الخبراء لتبسيط عمليات عملك.",
    service2: "التطوير",
    service2Desc: "حلول مخصصة مبنية بأحدث التقنيات.",
    service3: "الدعم",
    service3Desc: "دعم مخصص على مدار الساعة لجميع عملائنا.",

    skillsTitle: "مهاراتنا",
    skillsDesc: "الخبرة في مجالات وتقنيات متعددة.",
    skill1: "تطوير Full Stack",
    skill2: "عمارة السحابة",
    skill3: "تصميم UI/UX",
    skill4: "DevOps والنشر",
    skill5: "إدارة قاعدة البيانات",
    skill6: "تطوير API",

    experienceTitle: "التجربة",
    experienceDesc: "سنوات من تقديم حلول عالية الجودة للعملاء المتنوعين.",
    exp1: "10+ سنوات خبرة صناعية",
    exp2: "500+ مشروع مكتمل",
    exp3: "100+ عميل راضي",
    exp4: "50+ عضو فريق",

    contactTitle: "تواصل معنا",
    contactDesc: "لديك أسئلة؟ نود أن نسمع منك. تواصل معنا اليوم.",
    contactEmail: "البريد الإلكتروني: salimabdu759@gmail.com",
    contactPhone: "الهاتف: +250739390715-0735281339",
    contactAddress: "العنوان:  Main idea, City, kigali Rwanda",
    sendMessage: "إرسال رسالة",
  },
};
